// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Plantry.Catalog.Infrastructure;

#nullable disable

namespace Plantry.Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260711135736_AddUnitDisplayStyle")]
    partial class AddUnitDisplayStyle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Plantry.Catalog.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<int?>("DefaultDueDays")
                        .HasColumnType("integer")
                        .HasColumnName("default_due_days");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<int?>("Hue")
                        .HasColumnType("integer")
                        .HasColumnName("hue");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "Name")
                        .IsUnique();

                    b.ToTable("categories", "catalog");
                });

            modelBuilder.Entity("Plantry.Catalog.Domain.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("location_type");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "Name")
                        .IsUnique();

                    b.ToTable("locations", "catalog");
                });

            modelBuilder.Entity("Plantry.Catalog.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DefaultDueDays")
                        .HasColumnType("integer")
                        .HasColumnName("default_due_days");

                    b.Property<int?>("DefaultDueDaysAfterFreezing")
                        .HasColumnType("integer")
                        .HasColumnName("default_due_days_after_freezing");

                    b.Property<int?>("DefaultDueDaysAfterOpening")
                        .HasColumnType("integer")
                        .HasColumnName("default_due_days_after_opening");

                    b.Property<int?>("DefaultDueDaysAfterThawing")
                        .HasColumnType("integer")
                        .HasColumnName("default_due_days_after_thawing");

                    b.Property<Guid?>("DefaultLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_location_id");

                    b.Property<Guid>("DefaultUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_unit_id");

                    b.Property<bool>("HasVariants")
                        .HasColumnType("boolean")
                        .HasColumnName("has_variants");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_product_id");

                    b.Property<bool>("TrackStock")
                        .HasColumnType("boolean")
                        .HasColumnName("track_stock");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("HouseholdId", "Name")
                        .IsUnique();

                    b.ToTable("products", "catalog");
                });

            modelBuilder.Entity("Plantry.Catalog.Domain.ProductConversion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Factor")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("factor");

                    b.Property<Guid>("FromUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_unit_id");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<Guid>("ToUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_unit_id");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("ProductId");

                    b.ToTable("product_conversions", "catalog");
                });

            modelBuilder.Entity("Plantry.Catalog.Domain.ProductSku", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal?>("SizeQuantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("size_quantity");

                    b.Property<Guid?>("SizeUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("size_unit_id");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("ProductId");

                    b.ToTable("product_skus", "catalog");
                });

            modelBuilder.Entity("Plantry.Catalog.Domain.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_ref");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "ExternalRef")
                        .IsUnique()
                        .HasFilter("external_ref IS NOT NULL");

                    b.HasIndex("HouseholdId", "Name")
                        .IsUnique();

                    b.ToTable("stores", "catalog");
                });

            modelBuilder.Entity("Plantry.Catalog.Domain.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("dimension");

                    b.Property<string>("DisplayStyle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("display_style");

                    b.Property<decimal>("FactorToBase")
                        .HasColumnType("numeric")
                        .HasColumnName("factor_to_base");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<bool>("IsBase")
                        .HasColumnType("boolean")
                        .HasColumnName("is_base");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "Code")
                        .IsUnique();

                    b.ToTable("units", "catalog");
                });

            modelBuilder.Entity("Plantry.Catalog.Domain.ProductConversion", b =>
                {
                    b.HasOne("Plantry.Catalog.Domain.Product", null)
                        .WithMany("Conversions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Plantry.Catalog.Domain.ProductSku", b =>
                {
                    b.HasOne("Plantry.Catalog.Domain.Product", null)
                        .WithMany("Skus")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Plantry.Catalog.Domain.Product", b =>
                {
                    b.Navigation("Conversions");

                    b.Navigation("Skus");
                });
#pragma warning restore 612, 618
        }
    }
}
