// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Plantry.Inventory.Infrastructure;

#nullable disable

namespace Plantry.Inventory.Infrastructure.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260721233038_AddAmendmentReason")]
    partial class AddAmendmentReason
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Plantry.Inventory.Domain.HouseholdInventorySettings", b =>
                {
                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<int>("ExpiringSoonDays")
                        .HasColumnType("integer")
                        .HasColumnName("expiring_soon_days");

                    b.HasKey("HouseholdId");

                    b.ToTable("household_inventory_settings", "inventory");
                });

            modelBuilder.Entity("Plantry.Inventory.Domain.ProductStock", b =>
                {
                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("LowStockThreshold")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("low_stock_threshold");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("HouseholdId", "ProductId");

                    b.ToTable("product_stock", "inventory");
                });

            modelBuilder.Entity("Plantry.Inventory.Domain.StockEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DepletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("depleted_at");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<DateTimeOffset?>("FrozenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("frozen_at");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean")
                        .HasColumnName("is_open");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<DateOnly?>("PurchasedAt")
                        .HasColumnType("date")
                        .HasColumnName("purchased_at");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<DateTimeOffset?>("ThawedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("thawed_at");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "LocationId", "ProductId")
                        .HasDatabaseName("ix_stock_entry_by_location")
                        .HasFilter("depleted_at IS NULL");

                    b.HasIndex("HouseholdId", "ProductId", "ExpiryDate", "CreatedAt")
                        .HasDatabaseName("ix_stock_entry_fefo");

                    b.ToTable("stock_entry", "inventory");
                });

            modelBuilder.Entity("Plantry.Inventory.Domain.StockJournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_id");

                    b.Property<decimal>("Delta")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("delta");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reason");

                    b.Property<Guid?>("SourceLineRef")
                        .HasColumnType("uuid")
                        .HasColumnName("source_line_ref");

                    b.Property<Guid?>("SourceRef")
                        .HasColumnType("uuid")
                        .HasColumnName("source_ref");

                    b.Property<string>("SourceType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source_type");

                    b.Property<Guid>("StockEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("StockEntryId");

                    b.HasIndex("HouseholdId", "ProductId");

                    b.HasIndex("HouseholdId", "SourceRef", "SourceLineRef")
                        .HasDatabaseName("ix_stock_journal_idempotency");

                    b.ToTable("stock_journal_entry", "inventory");
                });

            modelBuilder.Entity("Plantry.Inventory.Domain.StockEntry", b =>
                {
                    b.HasOne("Plantry.Inventory.Domain.ProductStock", null)
                        .WithMany("Entries")
                        .HasForeignKey("HouseholdId", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Plantry.Inventory.Domain.StockJournalEntry", b =>
                {
                    b.HasOne("Plantry.Inventory.Domain.StockEntry", null)
                        .WithMany()
                        .HasForeignKey("StockEntryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Plantry.Inventory.Domain.ProductStock", null)
                        .WithMany("Journal")
                        .HasForeignKey("HouseholdId", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Plantry.Inventory.Domain.ProductStock", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Journal");
                });
#pragma warning restore 612, 618
        }
    }
}
