// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Plantry.Recipes.Infrastructure;

#nullable disable

namespace Plantry.Recipes.Infrastructure.Migrations
{
    [DbContext(typeof(RecipesDbContext))]
    partial class RecipesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("recipes")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Plantry.Recipes.Domain.CookConsumeLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("cook_consume_line_id");

                    b.Property<Guid>("CookEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("cook_event_id");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingredient_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("Shortfall")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("shortfall");

                    b.Property<Guid?>("SourceRecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_recipe_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("Id");

                    b.HasIndex("CookEventId");

                    b.HasIndex("HouseholdId", "CookEventId", "Status")
                        .HasDatabaseName("ix_cook_consume_line_household_event_status");

                    b.ToTable("cook_consume_line", "recipes");
                });

            modelBuilder.Entity("Plantry.Recipes.Domain.CookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("cook_event_id");

                    b.Property<DateTimeOffset>("CookedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cooked_at");

                    b.Property<Guid>("CookedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("cooked_by");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<int>("ServingsCooked")
                        .HasColumnType("integer")
                        .HasColumnName("servings_cooked");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "RecipeId", "CookedAt")
                        .HasDatabaseName("ix_cook_event_household_recipe_cooked");

                    b.ToTable("cook_event", "recipes");
                });

            modelBuilder.Entity("Plantry.Recipes.Domain.Inclusion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("inclusion_id");

                    b.Property<string>("GroupHeading")
                        .HasColumnType("text")
                        .HasColumnName("group_heading");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<decimal>("Servings")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("servings");

                    b.Property<Guid>("SubRecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("sub_recipe_id");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "SubRecipeId")
                        .HasDatabaseName("ix_recipe_inclusion_household_sub");

                    b.HasIndex("RecipeId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ux_recipe_inclusion_recipe_ordinal");

                    b.ToTable("recipe_inclusion", "recipes");
                });

            modelBuilder.Entity("Plantry.Recipes.Domain.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ingredient_id");

                    b.Property<string>("GroupHeading")
                        .HasColumnType("text")
                        .HasColumnName("group_heading");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ux_recipe_ingredient_recipe_ordinal");

                    b.ToTable("recipe_ingredient", "recipes");
                });

            modelBuilder.Entity("Plantry.Recipes.Domain.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<int?>("CookTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("cook_time_minutes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DefaultServings")
                        .HasColumnType("integer")
                        .HasColumnName("default_servings");

                    b.Property<string>("DietNudgeDismissedHash")
                        .HasColumnType("text")
                        .HasColumnName("diet_nudge_dismissed_hash");

                    b.Property<string>("Directions")
                        .HasColumnType("text")
                        .HasColumnName("directions");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "CookTimeMinutes")
                        .HasDatabaseName("ix_recipe_household_cook_time");

                    b.HasIndex("HouseholdId", "CreatedAt")
                        .HasDatabaseName("ix_recipe_household_created");

                    b.HasIndex("HouseholdId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_recipe_household_name");

                    b.ToTable("recipe", "recipes");
                });

            modelBuilder.Entity("Plantry.Recipes.Domain.RecipePhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<byte[]>("Sha256")
                        .HasColumnType("bytea")
                        .HasColumnName("sha256");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("recipe_photo", "recipes");
                });

            modelBuilder.Entity("Plantry.Recipes.Domain.RecipeTag", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.HasKey("RecipeId", "TagId");

                    b.HasIndex("HouseholdId", "TagId")
                        .HasDatabaseName("ix_recipe_tag_household_tag");

                    b.ToTable("recipe_tag", "recipes");
                });

            modelBuilder.Entity("Plantry.Recipes.Domain.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_tag_household_name");

                    b.ToTable("tag", "recipes");
                });

            modelBuilder.Entity("Plantry.Recipes.Domain.CookConsumeLine", b =>
                {
                    b.HasOne("Plantry.Recipes.Domain.CookEvent", null)
                        .WithMany("ConsumeLines")
                        .HasForeignKey("CookEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Plantry.Recipes.Domain.Inclusion", b =>
                {
                    b.HasOne("Plantry.Recipes.Domain.Recipe", null)
                        .WithMany("Inclusions")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Plantry.Recipes.Domain.Ingredient", b =>
                {
                    b.HasOne("Plantry.Recipes.Domain.Recipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Plantry.Recipes.Domain.RecipePhoto", b =>
                {
                    b.HasOne("Plantry.Recipes.Domain.Recipe", null)
                        .WithOne("Photo")
                        .HasForeignKey("Plantry.Recipes.Domain.RecipePhoto", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Plantry.Recipes.Domain.RecipeTag", b =>
                {
                    b.HasOne("Plantry.Recipes.Domain.Recipe", null)
                        .WithMany("Tags")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Plantry.Recipes.Domain.CookEvent", b =>
                {
                    b.Navigation("ConsumeLines");
                });

            modelBuilder.Entity("Plantry.Recipes.Domain.Recipe", b =>
                {
                    b.Navigation("Inclusions");

                    b.Navigation("Ingredients");

                    b.Navigation("Photo");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
