// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Plantry.Pricing.Infrastructure;

#nullable disable

namespace Plantry.Pricing.Infrastructure.Migrations
{
    [DbContext(typeof(PricingDbContext))]
    [Migration("20260722014504_AddPriceObservationAmendmentColumns")]
    partial class AddPriceObservationAmendmentColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pricing")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Plantry.Pricing.Domain.PriceObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("observation_id");

                    b.Property<Guid?>("AmendsId")
                        .HasColumnType("uuid")
                        .HasColumnName("amends_id");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("MerchantText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("merchant_text");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<Guid?>("SourceRef")
                        .HasColumnType("uuid")
                        .HasColumnName("source_ref");

                    b.Property<Guid?>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<Guid?>("SupersededById")
                        .HasColumnType("uuid")
                        .HasColumnName("superseded_by_id");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("unit_price");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.HasKey("Id");

                    b.HasIndex("AmendsId");

                    b.HasIndex("SupersededById");

                    b.HasIndex("HouseholdId", "ProductId")
                        .HasDatabaseName("ix_price_observation_deal")
                        .HasFilter("source = 'Deal'");

                    b.HasIndex("HouseholdId", "ProductId", "ObservedAt")
                        .HasDatabaseName("ix_price_observation_product");

                    b.HasIndex("HouseholdId", "SkuId", "ObservedAt")
                        .HasDatabaseName("ix_price_observation_sku")
                        .HasFilter("sku_id IS NOT NULL");

                    b.ToTable("price_observation", "pricing", t =>
                        {
                            t.HasCheckConstraint("ck_price_observation_valid_window", "valid_from <= valid_to");
                        });
                });

            modelBuilder.Entity("Plantry.Pricing.Domain.PriceObservation", b =>
                {
                    b.HasOne("Plantry.Pricing.Domain.PriceObservation", null)
                        .WithMany()
                        .HasForeignKey("AmendsId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Plantry.Pricing.Domain.PriceObservation", null)
                        .WithMany()
                        .HasForeignKey("SupersededById")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
