// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Plantry.Housekeeping.Infrastructure;

#nullable disable

namespace Plantry.Housekeeping.Infrastructure.Migrations
{
    [DbContext(typeof(HousekeepingDbContext))]
    partial class HousekeepingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("housekeeping")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Plantry.Housekeeping.Domain.Dismissal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("dismissal_id");

                    b.Property<string>("DetectorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("detector_id");

                    b.Property<DateTimeOffset>("DismissedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dismissed_at_utc");

                    b.Property<string>("FactsFingerprint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("facts_fingerprint");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "DetectorId", "SubjectId")
                        .IsUnique()
                        .HasDatabaseName("ux_dismissal_household_detector_subject");

                    b.ToTable("dismissal", "housekeeping");
                });
#pragma warning restore 612, 618
        }
    }
}
