using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.AspNetCore.TestHost;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Plantry.Catalog.Domain;
using Plantry.Intake.Application;
using Plantry.Intake.Domain;
using Plantry.Inventory.Domain;
using Plantry.MealPlanning.Application;
using Plantry.SharedKernel;
using Plantry.SharedKernel.Domain;
using Plantry.SharedKernel.Tenancy;
using SystemClock = Plantry.SharedKernel.Domain.SystemClock;

namespace Plantry.Tests.Web.Infrastructure;

/// <summary>
/// Fixed sessions across every history status (receipt-intake-history.md H5) plus one fully-lined
/// committed session (H7/H8: a resolved line, a new-product line, and a dismissed line) for the
/// /Intake/History and /Intake/Session L4 tests.
/// </summary>
public static class IntakeHistoryFixture
{
    public static readonly Guid HouseholdAId = Guid.Parse("cccccccc-0000-0000-0000-000000000001");
    public static readonly Guid HouseholdBId = Guid.Parse("dddddddd-0000-0000-0000-000000000002");

    public static readonly Guid LocationId = Guid.Parse("33333333-2222-1111-1111-111111111111");
    public static readonly Guid CategoryId = Guid.Parse("44444444-2222-1111-1111-111111111111");

    private static readonly IClock Clock = SystemClock.Instance;

    /// <param name="existingProductId">The id of a real, resolvable Catalog product — generated
    /// by <see cref="Product.Create"/> in the caller (a domain entity's id cannot be pinned to a literal
    /// constant), so the fixture's line and the test's fake product repository agree on the same id.</param>
    /// <param name="unitId">Likewise generated by <see cref="Unit.Create"/> in the caller.</param>
    public static ImportSession BuildCommitted(Guid householdId, Guid existingProductId, Guid unitId)
    {
        var session = ImportSession.Start(HouseholdId.From(householdId), ImportSourceType.Receipt, Guid.Empty, Clock);
        var resolved = session.AddLine(1, "KS ORG SPINACH 454G", SuggestedConfidence.High, null, suggestedPrice: 5.99m);
        var newProduct = session.AddLine(2, "MILK 2% 4L", SuggestedConfidence.None, null, suggestedPrice: 6.79m);
        var dismissed = session.AddLine(3, "MEMBERSHIP RENEWAL", SuggestedConfidence.None, null, suggestedPrice: 65.00m);

        session.MarkReady("Costco Wholesale", Clock.UtcNow, new ReceiptMetadata(
            PurchaseDate: new DateOnly(2026, 7, 18), Total: 189.55m, Tax: 2.12m, ReceiptNumber: "4023-1188-7734",
            PaymentDescriptor: "Mastercard ****6021"));

        resolved.Confirm(existingProductId, null, 454m, unitId, LocationId, null, 5.99m);
        resolved.MarkCommitted(Guid.NewGuid(), null);

        newProduct.ConfirmAsNew("Milk 2%", CategoryId, 4m, unitId, LocationId, null, 6.79m);
        newProduct.MarkCommitted(Guid.NewGuid(), null, createdProductId: Guid.NewGuid());

        dismissed.Dismiss();

        session.MarkCommitted(Clock.UtcNow);
        return session;
    }

    public static ImportSession BuildReady(Guid householdId)
    {
        var session = ImportSession.Start(HouseholdId.From(householdId), ImportSourceType.Receipt, Guid.Empty, Clock);
        session.AddLine(1, "Bread", SuggestedConfidence.High, null, suggestedPrice: 3.5m);
        session.MarkReady("Farm Boy", Clock.UtcNow);
        return session;
    }

    public static ImportSession BuildFailed(Guid householdId)
    {
        var session = ImportSession.Start(HouseholdId.From(householdId), ImportSourceType.Receipt, Guid.Empty, Clock);
        session.MarkParsingFailed("unreadable image");
        return session;
    }

    public static ImportSession BuildDiscarded(Guid householdId)
    {
        var session = ImportSession.Start(HouseholdId.From(householdId), ImportSourceType.Receipt, Guid.Empty, Clock);
        session.MarkReady(null, Clock.UtcNow);
        session.Discard();
        return session;
    }
}

/// <summary>
/// In-memory <see cref="IImportSessionRepository"/> that mirrors the real EF repository's history-page
/// semantics (household scoping, Parsing exclusion, created-at cursor paging) closely enough to exercise
/// <see cref="GetIntakeHistoryQuery"/> and the Session-detail state guard end to end without a database.
/// <see cref="FindAsync"/> is tenant-scoped exactly like the real EF query filter (RLS defense-in-depth,
/// ADR-008): it only returns a session owned by the ambient household, so a foreign-household id 404s.
/// </summary>
public sealed class MultiSessionImportSessionRepository(ITenantContext tenant, params ImportSession[] sessions) : IImportSessionRepository
{
    private readonly List<ImportSession> _sessions = [.. sessions];

    public Task<ImportSession?> FindAsync(ImportSessionId sessionId, CancellationToken ct = default)
    {
        if (tenant.HouseholdId is not { } hid)
            return Task.FromResult<ImportSession?>(null);
        return Task.FromResult(_sessions.SingleOrDefault(s => s.Id == sessionId && s.HouseholdId.Value == hid));
    }

    public Task<List<ImportSession>> ListHistoryPageAsync(
        HouseholdId householdId, DateTimeOffset? beforeCreatedAt, int take, CancellationToken ct = default) =>
        Task.FromResult(_sessions
            .Where(s => s.HouseholdId == householdId &&
                        s.Status != ImportStatus.Parsing &&
                        (beforeCreatedAt == null || s.CreatedAt < beforeCreatedAt))
            .OrderByDescending(s => s.CreatedAt)
            .Take(take)
            .ToList());

    public Task<IReadOnlyList<ImportLineProvenanceRow>> FindLinesForProvenanceAsync(
        HouseholdId householdId, IReadOnlyCollection<Guid> lineIds, IReadOnlyCollection<Guid> legacyJournalIds,
        CancellationToken ct = default) =>
        Task.FromResult<IReadOnlyList<ImportLineProvenanceRow>>([]);

    // Unused by the History/Session pages under test:
    public Task AddAsync(ImportSession session, CancellationToken ct = default) => Task.CompletedTask;
    public Task AddReceiptAsync(ImportReceipt receipt, CancellationToken ct = default) => Task.CompletedTask;
    public Task<ImportReceipt?> FindReceiptAsync(ImportSessionId sessionId, CancellationToken ct = default) => Task.FromResult<ImportReceipt?>(null);
    public Task SaveChangesAsync(CancellationToken ct = default) => Task.CompletedTask;
    public Task<List<ImportSession>> ListPendingAsync(HouseholdId householdId, CancellationToken ct = default) => Task.FromResult(new List<ImportSession>());
    public Task<bool> HasPendingAsync(HouseholdId householdId, CancellationToken ct = default) => Task.FromResult(false);
    public Task<List<ImportSession>> ListRecentAsync(HouseholdId householdId, int take = 10, CancellationToken ct = default) =>
        Task.FromResult(_sessions.Where(s => s.HouseholdId == householdId).OrderByDescending(s => s.CreatedAt).Take(take).ToList());
    public Task<List<ImportSession>> ListInMonthWindowAsync(HouseholdId householdId, DateTimeOffset windowStart, DateTimeOffset windowEnd, CancellationToken ct = default) =>
        Task.FromResult(new List<ImportSession>());
}

/// <summary>Single-product Catalog stand-in for the Session detail page's product-link resolution
/// (H10): wraps one real, already-constructed <see cref="Product"/> — a domain entity's id is minted by
/// <see cref="Product.Create"/> and cannot be pinned to a literal constant, so the caller builds the
/// product once and feeds its real id into both this repository and the session fixture's lines.</summary>
public sealed class FakeSessionProductRepository(Product product) : IProductRepository
{
    public Task<Product?> FindAsync(ProductId id, CancellationToken ct = default) =>
        Task.FromResult(id == product.Id ? product : null);
    public Task<Product?> FindByNameAsync(string name, CancellationToken ct = default) => Task.FromResult<Product?>(null);
    public Task<List<Product>> ListActiveAsync(CancellationToken ct = default) => Task.FromResult(new List<Product>());
    public Task<List<Product>> ListActiveWithSkusAsync(CancellationToken ct = default) => Task.FromResult(new List<Product>());
    public Task<List<Product>> ListWithConversionsAsync(IEnumerable<ProductId> ids, CancellationToken ct = default) => Task.FromResult(new List<Product>());
    public Task<List<Product>> ListVariantsAsync(ProductId parentId, CancellationToken ct = default) => Task.FromResult(new List<Product>());
    public Task AddAsync(Product p, CancellationToken ct = default) => Task.CompletedTask;
    public Task SaveChangesAsync(CancellationToken ct = default) => Task.CompletedTask;
}

/// <summary>Wraps one real, already-constructed <see cref="Unit"/> (see <see cref="FakeSessionProductRepository"/>
/// for why a literal constant id doesn't work here).</summary>
public sealed class FakeSessionUnitRepository(Unit unit) : IUnitRepository
{
    public Task<Unit?> FindAsync(Plantry.Catalog.Domain.UnitId id, CancellationToken ct = default) =>
        Task.FromResult(id == unit.Id ? unit : null);
    public Task<Unit?> FindByCodeAsync(string code, CancellationToken ct = default) => Task.FromResult<Unit?>(null);
    public Task<List<Unit>> ListAsync(CancellationToken ct = default) => Task.FromResult(new List<Unit>());
    public Task AddAsync(Unit u, CancellationToken ct = default) => Task.CompletedTask;
    public Task SaveChangesAsync(CancellationToken ct = default) => Task.CompletedTask;
}

/// <summary><paramref name="stockedProductIds"/> holds a stock record; anything else doesn't (drives the
/// pantry-vs-catalog product-link fallback, H10).</summary>
public sealed class FakeSessionStockRepository(params Guid[] stockedProductIds) : IProductStockRepository
{
    public Task<ProductStock?> FindForUpdateAsync(HouseholdId householdId, Guid productId, CancellationToken ct = default) => FindAsync(householdId, productId, ct);
    public Task<ProductStock?> FindAsync(HouseholdId householdId, Guid productId, CancellationToken ct = default) =>
        Task.FromResult(stockedProductIds.Contains(productId) ? ProductStock.Start(householdId, productId, SystemClock.Instance) : null);
    public Task<ProductStock?> FindWithHistoryAsync(HouseholdId householdId, Guid productId, CancellationToken ct = default) => FindAsync(householdId, productId, ct);
    public Task<List<ProductStock>> ListForHouseholdAsync(HouseholdId householdId, CancellationToken ct = default) => Task.FromResult(new List<ProductStock>());
    public Task<bool> AnyForHouseholdAsync(HouseholdId householdId, CancellationToken ct = default) => Task.FromResult(stockedProductIds.Length > 0);
    public Task AddAsync(ProductStock stock, CancellationToken ct = default) => Task.CompletedTask;
    public Task<bool> TryAddAndSaveAsync(ProductStock stock, CancellationToken ct = default) => Task.FromResult(true);
    public Task SaveChangesAsync(CancellationToken ct = default) => Task.CompletedTask;
    public Task<T> ExecuteInTransactionAsync<T>(Func<CancellationToken, Task<T>> work, CancellationToken ct = default) => work(ct);
}

public sealed class FakeSessionMemberReader : IHouseholdMemberReader
{
    public Task<IReadOnlyList<HouseholdMember>> ListMembersAsync(CancellationToken ct = default) =>
        Task.FromResult<IReadOnlyList<HouseholdMember>>([new HouseholdMember(Guid.Empty, "Michael", "M")]);
}

/// <summary>
/// L4 WebApplicationFactory for the /Intake/History and /Intake/Session pages (receipt-intake-history.md
/// H5/H7). Swaps every Postgres-backed seam for an in-memory fake so both pages render without a database.
/// </summary>
public sealed class IntakeHistorySessionFragmentFactory : WebApplicationFactory<Program>
{
    public Unit ExistingUnit { get; } = Unit.Create(
        HouseholdId.From(IntakeHistoryFixture.HouseholdAId), "g", "Gram", Dimension.Mass, 1m, isBase: true);

    public Product ExistingProduct { get; }

    public ImportSession Committed { get; }
    public ImportSession Ready { get; } = IntakeHistoryFixture.BuildReady(IntakeHistoryFixture.HouseholdAId);
    public ImportSession Failed { get; } = IntakeHistoryFixture.BuildFailed(IntakeHistoryFixture.HouseholdAId);
    public ImportSession Discarded { get; } = IntakeHistoryFixture.BuildDiscarded(IntakeHistoryFixture.HouseholdAId);
    public ImportSession ForeignCommitted { get; }

    public IntakeHistorySessionFragmentFactory()
    {
        ExistingProduct = Product.Create(
            HouseholdId.From(IntakeHistoryFixture.HouseholdAId), "Baby spinach", ExistingUnit.Id, SystemClock.Instance);
        Committed = IntakeHistoryFixture.BuildCommitted(IntakeHistoryFixture.HouseholdAId, ExistingProduct.Id.Value, ExistingUnit.Id.Value);
        ForeignCommitted = IntakeHistoryFixture.BuildCommitted(IntakeHistoryFixture.HouseholdBId, ExistingProduct.Id.Value, ExistingUnit.Id.Value);
    }

    protected override void ConfigureWebHost(IWebHostBuilder builder)
    {
        builder.UseEnvironment("Testing");

        builder.ConfigureTestServices(services =>
        {
            services.AddFakeDisplayCurrency();
            services.AddAuthentication(options =>
                {
                    options.DefaultScheme = TestAuthHandler.SchemeName;
                    options.DefaultAuthenticateScheme = TestAuthHandler.SchemeName;
                    options.DefaultChallengeScheme = TestAuthHandler.SchemeName;
                })
                .AddScheme<AuthenticationSchemeOptions, TestAuthHandler>(TestAuthHandler.SchemeName, _ => { });

            services.RemoveAll<IImportSessionRepository>();
            services.AddScoped<IImportSessionRepository>(sp => new MultiSessionImportSessionRepository(
                sp.GetRequiredService<ITenantContext>(), Committed, Ready, Failed, Discarded, ForeignCommitted));

            services.RemoveAll<Plantry.Catalog.Domain.IProductRepository>();
            services.AddScoped<Plantry.Catalog.Domain.IProductRepository>(
                _ => new FakeSessionProductRepository(ExistingProduct));

            services.RemoveAll<Plantry.Catalog.Domain.IUnitRepository>();
            services.AddScoped<Plantry.Catalog.Domain.IUnitRepository>(
                _ => new FakeSessionUnitRepository(ExistingUnit));

            services.RemoveAll<IProductStockRepository>();
            services.AddScoped<IProductStockRepository>(
                _ => new FakeSessionStockRepository(ExistingProduct.Id.Value));

            services.RemoveAll<IHouseholdMemberReader>();
            services.AddScoped<IHouseholdMemberReader, FakeSessionMemberReader>();
        });
    }

    public HttpClient CreateAuthClient(Guid householdId)
    {
        var client = CreateClient();
        client.DefaultRequestHeaders.Add(TestAuthHandler.HouseholdHeader, householdId.ToString());
        return client;
    }
}
