// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Plantry.MealPlanning.Infrastructure;

#nullable disable

namespace Plantry.MealPlanning.Infrastructure.Migrations
{
    [DbContext(typeof(MealPlanningDbContext))]
    [Migration("20260617143350_MakePlannedMealSlotConstraintDeferrable")]
    partial class MakePlannedMealSlotConstraintDeferrable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("meal_planning")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Plantry.MealPlanning.Domain.MealPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("meal_plan_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date")
                        .HasColumnName("week_start");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "Id")
                        .IsUnique()
                        .HasDatabaseName("ux_meal_plan_household_id");

                    b.HasIndex("HouseholdId", "WeekStart")
                        .IsUnique()
                        .HasDatabaseName("ux_meal_plan_household_week");

                    b.ToTable("meal_plan", "meal_planning");
                });

            modelBuilder.Entity("Plantry.MealPlanning.Domain.MealSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("meal_slot_id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<Guid>("ConfigId")
                        .HasColumnType("uuid")
                        .HasColumnName("meal_slot_config_id");

                    b.PrimitiveCollection<List<Guid>>("DefaultAttendees")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid[]")
                        .HasColumnName("default_attendees")
                        .HasDefaultValueSql("'{}'::uuid[]");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.HasKey("Id");

                    b.HasIndex("ConfigId");

                    b.HasIndex("HouseholdId", "Id")
                        .IsUnique()
                        .HasDatabaseName("ux_meal_slot_household_id");

                    b.ToTable("meal_slot", "meal_planning");
                });

            modelBuilder.Entity("Plantry.MealPlanning.Domain.MealSlotConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("meal_slot_config_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId")
                        .IsUnique()
                        .HasDatabaseName("ux_meal_slot_config_household");

                    b.HasIndex("HouseholdId", "Id")
                        .IsUnique()
                        .HasDatabaseName("ux_meal_slot_config_household_id");

                    b.ToTable("meal_slot_config", "meal_planning");
                });

            modelBuilder.Entity("Plantry.MealPlanning.Domain.PlannedDish", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("planned_dish_id");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<Guid>("PlannedMealId")
                        .HasColumnType("uuid")
                        .HasColumnName("planned_meal_id");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<int>("Servings")
                        .HasColumnType("integer")
                        .HasColumnName("servings");

                    b.HasKey("Id");

                    b.HasIndex("PlannedMealId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ux_planned_dish_meal_ordinal");

                    b.ToTable("planned_dish", "meal_planning");
                });

            modelBuilder.Entity("Plantry.MealPlanning.Domain.PlannedMeal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("planned_meal_id");

                    b.PrimitiveCollection<List<Guid>>("AttendeesOverride")
                        .HasColumnType("uuid[]")
                        .HasColumnName("attendees_override");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<Guid>("MealPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("meal_plan_id");

                    b.Property<Guid>("MealSlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("meal_slot_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Reasoning")
                        .HasColumnType("text")
                        .HasColumnName("reasoning");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "Id")
                        .IsUnique()
                        .HasDatabaseName("ux_planned_meal_household_id");

                    b.HasIndex("MealPlanId", "Date", "MealSlotId")
                        .IsUnique()
                        .HasDatabaseName("ux_planned_meal_plan_date_slot");

                    b.ToTable("planned_meal", "meal_planning");
                });

            modelBuilder.Entity("Plantry.MealPlanning.Domain.TagStance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_stance_id");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("Stance")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stance");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<Guid>("UserPreferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_preference_id");

                    b.HasKey("Id");

                    b.HasIndex("UserPreferenceId", "TagId")
                        .IsUnique()
                        .HasDatabaseName("ux_tag_stance_pref_tag");

                    b.ToTable("tag_stance", "meal_planning");
                });

            modelBuilder.Entity("Plantry.MealPlanning.Domain.UserPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("user_preference_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "Id")
                        .IsUnique()
                        .HasDatabaseName("ux_user_preference_household_id");

                    b.HasIndex("HouseholdId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_user_preference_household_user");

                    b.ToTable("user_preference", "meal_planning");
                });

            modelBuilder.Entity("Plantry.MealPlanning.Domain.MealSlot", b =>
                {
                    b.HasOne("Plantry.MealPlanning.Domain.MealSlotConfig", null)
                        .WithMany("Slots")
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Plantry.MealPlanning.Domain.PlannedDish", b =>
                {
                    b.HasOne("Plantry.MealPlanning.Domain.PlannedMeal", null)
                        .WithMany("PlannedDishes")
                        .HasForeignKey("PlannedMealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Plantry.MealPlanning.Domain.PlannedMeal", b =>
                {
                    b.HasOne("Plantry.MealPlanning.Domain.MealPlan", null)
                        .WithMany("PlannedMeals")
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Plantry.MealPlanning.Domain.TagStance", b =>
                {
                    b.HasOne("Plantry.MealPlanning.Domain.UserPreference", null)
                        .WithMany("TagStances")
                        .HasForeignKey("UserPreferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Plantry.MealPlanning.Domain.MealPlan", b =>
                {
                    b.Navigation("PlannedMeals");
                });

            modelBuilder.Entity("Plantry.MealPlanning.Domain.MealSlotConfig", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("Plantry.MealPlanning.Domain.PlannedMeal", b =>
                {
                    b.Navigation("PlannedDishes");
                });

            modelBuilder.Entity("Plantry.MealPlanning.Domain.UserPreference", b =>
                {
                    b.Navigation("TagStances");
                });
#pragma warning restore 612, 618
        }
    }
}
