// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Plantry.Deals.Infrastructure;

#nullable disable

namespace Plantry.Deals.Infrastructure.Migrations
{
    [DbContext(typeof(DealsDbContext))]
    [Migration("20260707012813_FlyerImportDedupParsedOnly")]
    partial class FlyerImportDedupParsedOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("deals")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Plantry.Deals.Domain.Deal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("deal_id");

                    b.Property<bool>("AutoMatched")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("auto_matched");

                    b.Property<string>("Brand")
                        .HasColumnType("text")
                        .HasColumnName("brand");

                    b.Property<Guid?>("CommittedPriceObservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("committed_price_observation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("FlyerImportId")
                        .HasColumnType("uuid")
                        .HasColumnName("flyer_import_id");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("MatchConfidence")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("match_confidence");

                    b.Property<string>("MatchReasoning")
                        .HasColumnType("text")
                        .HasColumnName("match_reasoning");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_name");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity");

                    b.Property<string>("RawName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_name");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("SaleStory")
                        .HasColumnType("text")
                        .HasColumnName("sale_story");

                    b.Property<string>("Size")
                        .HasColumnType("text")
                        .HasColumnName("size");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<Guid?>("SuggestedProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("suggested_product_id");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ValidityWindow", "Plantry.Deals.Domain.Deal.ValidityWindow#ValidityWindow", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("ValidFrom")
                                .HasColumnType("date")
                                .HasColumnName("valid_from");

                            b1.Property<DateOnly>("ValidTo")
                                .HasColumnType("date")
                                .HasColumnName("valid_to");
                        });

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "FlyerImportId")
                        .HasDatabaseName("ix_deal_household_flyer_import");

                    b.HasIndex("HouseholdId", "StoreId", "Status")
                        .HasDatabaseName("ix_deal_household_store_status");

                    b.ToTable("deal", "deals");
                });

            modelBuilder.Entity("Plantry.Deals.Domain.DealMatchMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("deal_match_memory_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<Guid?>("LastConfirmedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_confirmed_by_user_id");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_name");

                    b.Property<int>("NormalizerVersion")
                        .HasColumnType("integer")
                        .HasColumnName("normalizer_version");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("RawName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_name");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "StoreId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_deal_match_memory_household_store_name");

                    b.ToTable("deal_match_memory", "deals");
                });

            modelBuilder.Entity("Plantry.Deals.Domain.FlyerImport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("flyer_import_id");

                    b.Property<byte[]>("ContentHash")
                        .HasColumnType("bytea")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorDetail")
                        .HasColumnType("text")
                        .HasColumnName("error_detail");

                    b.Property<string>("FlyerExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flyer_external_id");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<DateTimeOffset?>("ParsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("parsed_at");

                    b.Property<DateTimeOffset>("PulledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pulled_at");

                    b.Property<string>("RawFlyer")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_flyer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ValidityWindow", "Plantry.Deals.Domain.FlyerImport.ValidityWindow#ValidityWindow", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("ValidFrom")
                                .HasColumnType("date")
                                .HasColumnName("valid_from");

                            b1.Property<DateOnly>("ValidTo")
                                .HasColumnType("date")
                                .HasColumnName("valid_to");
                        });

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "Id")
                        .IsUnique()
                        .HasDatabaseName("ux_flyer_import_household_id");

                    b.HasIndex("HouseholdId", "StoreId", "FlyerExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_flyer_import_household_store_external")
                        .HasFilter("status = 'parsed'");

                    b.ToTable("flyer_import", "deals");
                });

            modelBuilder.Entity("Plantry.Deals.Domain.StoreSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("store_subscription_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LastFlyerExternalId")
                        .HasColumnType("text")
                        .HasColumnName("last_flyer_external_id");

                    b.Property<DateTimeOffset?>("LastPulledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_pulled_at");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "StoreId")
                        .IsUnique()
                        .HasDatabaseName("ux_store_subscription_household_store");

                    b.ToTable("store_subscription", "deals");
                });
#pragma warning restore 612, 618
        }
    }
}
