// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Plantry.Planning.Infrastructure;

#nullable disable

namespace Plantry.Planning.Infrastructure.Migrations.Planning
{
    [DbContext(typeof(PlanningDbContext))]
    partial class PlanningDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("shopping")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Plantry.Planning.Domain.HouseholdPlanningSettings", b =>
                {
                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.HasKey("HouseholdId");

                    b.ToTable("household_planning_settings", "meal_planning");
                });

            modelBuilder.Entity("Plantry.Planning.Domain.MealPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("meal_plan_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date")
                        .HasColumnName("week_start");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "Id")
                        .IsUnique()
                        .HasDatabaseName("ux_meal_plan_household_id");

                    b.HasIndex("HouseholdId", "WeekStart")
                        .IsUnique()
                        .HasDatabaseName("ux_meal_plan_household_week");

                    b.ToTable("meal_plan", "meal_planning");
                });

            modelBuilder.Entity("Plantry.Planning.Domain.MealSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("meal_slot_id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<Guid>("ConfigId")
                        .HasColumnType("uuid")
                        .HasColumnName("meal_slot_config_id");

                    b.PrimitiveCollection<List<Guid>>("DefaultAttendees")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid[]")
                        .HasColumnName("default_attendees")
                        .HasDefaultValueSql("'{}'::uuid[]");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<bool>("IncludeInAutoPlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("include_in_auto_plan");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.HasKey("Id");

                    b.HasIndex("ConfigId");

                    b.HasIndex("HouseholdId", "Id")
                        .IsUnique()
                        .HasDatabaseName("ux_meal_slot_household_id");

                    b.ToTable("meal_slot", "meal_planning");
                });

            modelBuilder.Entity("Plantry.Planning.Domain.MealSlotConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("meal_slot_config_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId")
                        .IsUnique()
                        .HasDatabaseName("ux_meal_slot_config_household");

                    b.HasIndex("HouseholdId", "Id")
                        .IsUnique()
                        .HasDatabaseName("ux_meal_slot_config_household_id");

                    b.ToTable("meal_slot_config", "meal_planning");
                });

            modelBuilder.Entity("Plantry.Planning.Domain.PlannedDish", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("planned_dish_id");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<Guid>("PlannedMealId")
                        .HasColumnType("uuid")
                        .HasColumnName("planned_meal_id");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<int?>("Servings")
                        .HasColumnType("integer")
                        .HasColumnName("servings");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("Id");

                    b.HasIndex("PlannedMealId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ux_planned_dish_meal_ordinal");

                    b.ToTable("planned_dish", "meal_planning", t =>
                        {
                            t.HasCheckConstraint("ck_planned_dish_shape", "((recipe_id IS NOT NULL AND product_id IS NULL AND servings IS NOT NULL AND servings >= 1 AND quantity IS NULL AND unit_id IS NULL) OR (recipe_id IS NULL AND product_id IS NOT NULL AND servings IS NULL AND quantity IS NOT NULL AND quantity > 0 AND unit_id IS NOT NULL AND unit_id <> '00000000-0000-0000-0000-000000000000'))");
                        });
                });

            modelBuilder.Entity("Plantry.Planning.Domain.PlannedMeal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("planned_meal_id");

                    b.PrimitiveCollection<List<Guid>>("AttendeesOverride")
                        .HasColumnType("uuid[]")
                        .HasColumnName("attendees_override");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<Guid>("MealPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("meal_plan_id");

                    b.Property<Guid>("MealSlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("meal_slot_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("Reasoning")
                        .HasColumnType("text")
                        .HasColumnName("reasoning");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "Id")
                        .IsUnique()
                        .HasDatabaseName("ux_planned_meal_household_id");

                    b.HasIndex("MealPlanId", "Date", "MealSlotId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ux_planned_meal_plan_date_slot_ordinal");

                    b.ToTable("planned_meal", "meal_planning");
                });

            modelBuilder.Entity("Plantry.Planning.Domain.ShoppingList", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("shopping_list_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "Id")
                        .IsUnique()
                        .HasDatabaseName("uq_shopping_list_household_list");

                    b.ToTable("shopping_list", "shopping");
                });

            modelBuilder.Entity("Plantry.Planning.Domain.ShoppingListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("shopping_list_item_id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset?>("CheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_at");

                    b.Property<Guid?>("CheckedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("checked_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FreeText")
                        .HasColumnType("text")
                        .HasColumnName("free_text");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("ShoppingListId")
                        .HasColumnType("uuid")
                        .HasColumnName("shopping_list_id");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ShoppingListId");

                    b.HasIndex("HouseholdId", "ShoppingListId")
                        .HasDatabaseName("ix_shopping_list_item_household_list");

                    b.ToTable("shopping_list_item", "shopping");
                });

            modelBuilder.Entity("Plantry.Planning.Domain.ShoppingListItemContribution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("contribution_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("shopping_list_item_id");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<Guid?>("SourceRef")
                        .HasColumnType("uuid")
                        .HasColumnName("source_ref");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_shopping_list_item_contribution_item");

                    b.ToTable("shopping_list_item_contribution", "shopping");
                });

            modelBuilder.Entity("Plantry.Planning.Domain.TagStance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_stance_id");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("Stance")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stance");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<Guid>("UserPreferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_preference_id");

                    b.HasKey("Id");

                    b.HasIndex("UserPreferenceId", "TagId")
                        .IsUnique()
                        .HasDatabaseName("ux_tag_stance_pref_tag");

                    b.ToTable("tag_stance", "meal_planning");
                });

            modelBuilder.Entity("Plantry.Planning.Domain.UserPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("user_preference_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "Id")
                        .IsUnique()
                        .HasDatabaseName("ux_user_preference_household_id");

                    b.HasIndex("HouseholdId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_user_preference_household_user");

                    b.ToTable("user_preference", "meal_planning");
                });

            modelBuilder.Entity("Plantry.Planning.Domain.WeekPlanningOverride", b =>
                {
                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date")
                        .HasColumnName("week_start");

                    b.HasKey("HouseholdId", "WeekStart");

                    b.ToTable("week_planning_override", "meal_planning");
                });

            modelBuilder.Entity("Plantry.Planning.Domain.HouseholdPlanningSettings", b =>
                {
                    b.OwnsOne("Plantry.Planning.Domain.PlanningWeights", "DefaultPlanningWeights", b1 =>
                        {
                            b1.Property<Guid>("HouseholdPlanningSettingsHouseholdId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Cost")
                                .HasColumnType("integer")
                                .HasColumnName("weights_cost");

                            b1.Property<int>("Variety")
                                .HasColumnType("integer")
                                .HasColumnName("weights_variety");

                            b1.Property<int>("Waste")
                                .HasColumnType("integer")
                                .HasColumnName("weights_waste");

                            b1.HasKey("HouseholdPlanningSettingsHouseholdId");

                            b1.ToTable("household_planning_settings", "meal_planning");

                            b1.WithOwner()
                                .HasForeignKey("HouseholdPlanningSettingsHouseholdId");
                        });

                    b.OwnsOne("Plantry.SharedKernel.Money", "DefaultWeeklyBudget", b1 =>
                        {
                            b1.Property<Guid>("HouseholdPlanningSettingsHouseholdId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("budget_currency");

                            b1.Property<long>("MinorUnits")
                                .HasColumnType("bigint")
                                .HasColumnName("budget_minor_units");

                            b1.HasKey("HouseholdPlanningSettingsHouseholdId");

                            b1.ToTable("household_planning_settings", "meal_planning");

                            b1.WithOwner()
                                .HasForeignKey("HouseholdPlanningSettingsHouseholdId");
                        });

                    b.Navigation("DefaultPlanningWeights");

                    b.Navigation("DefaultWeeklyBudget");
                });

            modelBuilder.Entity("Plantry.Planning.Domain.MealSlot", b =>
                {
                    b.HasOne("Plantry.Planning.Domain.MealSlotConfig", null)
                        .WithMany("Slots")
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Plantry.Planning.Domain.PlannedDish", b =>
                {
                    b.HasOne("Plantry.Planning.Domain.PlannedMeal", null)
                        .WithMany("PlannedDishes")
                        .HasForeignKey("PlannedMealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Plantry.Planning.Domain.PlannedMeal", b =>
                {
                    b.HasOne("Plantry.Planning.Domain.MealPlan", null)
                        .WithMany("PlannedMeals")
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Plantry.Planning.Domain.ShoppingListItem", b =>
                {
                    b.HasOne("Plantry.Planning.Domain.ShoppingList", null)
                        .WithMany("Items")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Plantry.Planning.Domain.ShoppingListItemContribution", b =>
                {
                    b.HasOne("Plantry.Planning.Domain.ShoppingListItem", null)
                        .WithMany("Contributions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Plantry.Planning.Domain.TagStance", b =>
                {
                    b.HasOne("Plantry.Planning.Domain.UserPreference", null)
                        .WithMany("TagStances")
                        .HasForeignKey("UserPreferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Plantry.Planning.Domain.WeekPlanningOverride", b =>
                {
                    b.OwnsOne("Plantry.SharedKernel.Money", "BudgetOverride", b1 =>
                        {
                            b1.Property<Guid>("WeekPlanningOverrideHouseholdId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("WeekPlanningOverrideWeekStart")
                                .HasColumnType("date");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("budget_currency");

                            b1.Property<long>("MinorUnits")
                                .HasColumnType("bigint")
                                .HasColumnName("budget_minor_units");

                            b1.HasKey("WeekPlanningOverrideHouseholdId", "WeekPlanningOverrideWeekStart");

                            b1.ToTable("week_planning_override", "meal_planning");

                            b1.WithOwner()
                                .HasForeignKey("WeekPlanningOverrideHouseholdId", "WeekPlanningOverrideWeekStart");
                        });

                    b.OwnsOne("Plantry.Planning.Domain.PlanningWeights", "WeightsOverride", b1 =>
                        {
                            b1.Property<Guid>("WeekPlanningOverrideHouseholdId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("WeekPlanningOverrideWeekStart")
                                .HasColumnType("date");

                            b1.Property<int>("Cost")
                                .HasColumnType("integer")
                                .HasColumnName("weights_cost");

                            b1.Property<int>("Variety")
                                .HasColumnType("integer")
                                .HasColumnName("weights_variety");

                            b1.Property<int>("Waste")
                                .HasColumnType("integer")
                                .HasColumnName("weights_waste");

                            b1.HasKey("WeekPlanningOverrideHouseholdId", "WeekPlanningOverrideWeekStart");

                            b1.ToTable("week_planning_override", "meal_planning");

                            b1.WithOwner()
                                .HasForeignKey("WeekPlanningOverrideHouseholdId", "WeekPlanningOverrideWeekStart");
                        });

                    b.Navigation("BudgetOverride");

                    b.Navigation("WeightsOverride");
                });

            modelBuilder.Entity("Plantry.Planning.Domain.MealPlan", b =>
                {
                    b.Navigation("PlannedMeals");
                });

            modelBuilder.Entity("Plantry.Planning.Domain.MealSlotConfig", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("Plantry.Planning.Domain.PlannedMeal", b =>
                {
                    b.Navigation("PlannedDishes");
                });

            modelBuilder.Entity("Plantry.Planning.Domain.ShoppingList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Plantry.Planning.Domain.ShoppingListItem", b =>
                {
                    b.Navigation("Contributions");
                });

            modelBuilder.Entity("Plantry.Planning.Domain.UserPreference", b =>
                {
                    b.Navigation("TagStances");
                });
#pragma warning restore 612, 618
        }
    }
}
